// blueprints/svelte/Component.blueprint.svelte
<!--
  BLUEPRINT: Svelte Component Wrapper (CSS-First Architecture)
  Thin wrapper — maps props to BEM classes. NO <style> block.
  Uses DS_PREFIX from @vcds/shared for the configurable prefix.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { DS_PREFIX } from '@vcds/shared/prefix';

  interface Props {
    variant?: string;
    size?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { variant = 'default', size = 'md', children, ...rest }: Props = $props();

  const p = DS_PREFIX;

  let rootClass = $derived(
    [
      `${p}-{{component-name}}`,
      `${p}-{{component-name}}--${variant}`,
      `${p}-{{component-name}}--${size}`,
    ].join(' ')
  );
</script>

<element class={rootClass} {...rest}>
  {#if children}{@render children()}{/if}
</element>

<!-- No <style> block — all styles from @vcds/css-components -->

// blueprints/vue/Component.blueprint.vue
<!--
  BLUEPRINT: Vue Component Wrapper (CSS-First Architecture)
  Thin wrapper — maps props to BEM classes. NO <style> block.
  Uses DS_PREFIX from @vcds/shared for the configurable prefix.
-->
<script setup lang="ts">
import { DS_PREFIX } from '@vcds/shared/prefix';

export interface Ds{{ComponentName}}Props {
  variant?: string;
  size?: string;
}

const props = withDefaults(defineProps<Ds{{ComponentName}}Props>(), {
  variant: 'default',
  size: 'md',
});

defineOptions({ name: 'Ds{{ComponentName}}' });

const p = DS_PREFIX;
</script>

<template>
  <element
    :class="[
      `${p}-{{component-name}}`,
      `${p}-{{component-name}}--${variant}`,
      `${p}-{{component-name}}--${size}`,
    ]"
  >
    <slot />
  </element>
</template>

<!-- No <style> block — all styles from @vcds/css-components -->
