// packages/svelte/src/components/Button/DsButton.svelte
<!--
  DsButton — Primary interactive element for triggering actions.

  Styles come from @vcds/css-components (BEM classes with configurable prefix).
  Prefix is defined in /ds.config.json — change with: node scripts/set-prefix.js
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { DS_PREFIX } from '@vcds/shared/prefix';

  type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
  type ButtonSize = 'sm' | 'md' | 'lg';

  interface Props {
    variant?: ButtonVariant;
    size?: ButtonSize;
    fullWidth?: boolean;
    isLoading?: boolean;
    disabled?: boolean;
    onclick?: (event: MouseEvent) => void;
    children?: Snippet;
    iconLeft?: Snippet;
    iconRight?: Snippet;
    [key: string]: unknown;
  }

  let {
    variant = 'primary',
    size = 'md',
    fullWidth = false,
    isLoading = false,
    disabled = false,
    onclick,
    children,
    iconLeft,
    iconRight,
    ...rest
  }: Props = $props();

  const p = DS_PREFIX;
  let isDisabled = $derived(disabled || isLoading);

  let buttonClass = $derived(
    [
      `${p}-button`,
      `${p}-button--${variant}`,
      `${p}-button--${size}`,
      fullWidth ? `${p}-button--full-width` : '',
      isLoading ? `${p}-button--loading` : '',
    ].filter(Boolean).join(' ')
  );

  function handleClick(event: MouseEvent) {
    if (!isDisabled && onclick) {
      onclick(event);
    }
  }
</script>

<button
  class={buttonClass}
  aria-disabled={isDisabled || undefined}
  aria-busy={isLoading || undefined}
  onclick={handleClick}
  {...rest}
>
  {#if isLoading}
    <span class="{p}-button__spinner" aria-hidden="true">
      <svg class="{p}-button__spinner-icon" viewBox="0 0 24 24" fill="none">
        <circle
          cx="12" cy="12" r="10"
          stroke="currentColor" stroke-width="3"
          stroke-linecap="round" stroke-dasharray="31.42 31.42"
        />
      </svg>
    </span>
  {/if}

  {#if iconLeft && !isLoading}
    <span class="{p}-button__icon-left" aria-hidden="true">
      {@render iconLeft()}
    </span>
  {/if}

  <span class={isLoading ? `${p}-button__label--hidden` : `${p}-button__label`}>
    {#if children}
      {@render children()}
    {/if}
  </span>

  {#if isLoading}
    <span class="{p}-button__sr-only">Loading</span>
  {/if}

  {#if iconRight}
    <span class="{p}-button__icon-right" aria-hidden="true">
      {@render iconRight()}
    </span>
  {/if}
</button>

<!-- No <style> block — all styles come from @vcds/css-components -->

// packages/angular/src/components/Button/ds-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { NgClass, NgIf } from '@angular/common';
import { DS_PREFIX, cls } from '@vcds/shared/prefix';

/**
 * DsButton — Primary interactive element for triggering actions.
 *
 * Styles come from @vcds/css-components (BEM classes with configurable prefix).
 * Prefix is defined in /ds.config.json — change with: node scripts/set-prefix.js
 *
 * @example
 * ```html
 * <ds-button variant="primary" size="md" (clicked)="onSave()">
 *   Save changes
 * </ds-button>
 * ```
 */
@Component({
  selector: 'ds-button',
  standalone: true,
  imports: [NgClass, NgIf],
  template: `
    <button
      [ngClass]="buttonClasses"
      [attr.aria-disabled]="isButtonDisabled || null"
      [attr.aria-busy]="isLoading || null"
      (click)="handleClick($event)"
    >
      <span *ngIf="isLoading" [class]="spinnerClass" aria-hidden="true">
        <svg [class]="spinnerIconClass" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle
            cx="12" cy="12" r="10"
            stroke="currentColor" stroke-width="3"
            stroke-linecap="round" stroke-dasharray="31.42 31.42"
          />
        </svg>
      </span>

      <span *ngIf="!isLoading" [class]="iconLeftClass" aria-hidden="true">
        <ng-content select="[iconLeft]"></ng-content>
      </span>

      <span [class]="isLoading ? labelHiddenClass : labelClass">
        <ng-content></ng-content>
      </span>

      <span *ngIf="isLoading" [class]="srOnlyClass">Loading</span>

      <span [class]="iconRightClass" aria-hidden="true">
        <ng-content select="[iconRight]"></ng-content>
      </span>
    </button>
  `,
})
export class DsButtonComponent {
  /** Visual style variant */
  @Input() variant: 'primary' | 'secondary' | 'ghost' | 'danger' = 'primary';

  /** Size of the button */
  @Input() size: 'sm' | 'md' | 'lg' = 'md';

  /** Whether the button takes full width of its container */
  @Input() fullWidth = false;

  /** Whether the button is in a loading state */
  @Input() isLoading = false;

  /** Whether the button is disabled */
  @Input() disabled = false;

  /** Emitted when the button is clicked (not emitted when disabled or loading) */
  @Output() clicked = new EventEmitter<MouseEvent>();

  get isButtonDisabled(): boolean {
    return this.disabled || this.isLoading;
  }

  get buttonClasses(): string {
    return [
      cls('button'),
      cls('button', this.variant),
      cls('button', this.size),
      this.fullWidth ? cls('button', 'full-width') : '',
      this.isLoading ? cls('button', 'loading') : '',
    ]
      .filter(Boolean)
      .join(' ');
  }

  get spinnerClass(): string {
    return cls('button', null, 'spinner');
  }

  get spinnerIconClass(): string {
    return cls('button', null, 'spinner-icon');
  }

  get iconLeftClass(): string {
    return cls('button', null, 'icon-left');
  }

  get iconRightClass(): string {
    return cls('button', null, 'icon-right');
  }

  get labelClass(): string {
    return cls('button', null, 'label');
  }

  get labelHiddenClass(): string {
    return `${cls('button', null, 'label')}--hidden`;
  }

  get srOnlyClass(): string {
    return cls('button', null, 'sr-only');
  }

  handleClick(event: MouseEvent): void {
    if (!this.isButtonDisabled) {
      this.clicked.emit(event);
    }
  }
}
